export const ENTRY = 'Entry';
export const ENTRY_LIST = 'Entries';
export const FILLUP = 'Fill-up';
export const SERVICE = 'Service';
export const NEW_FILLUP = 'New Fill-up';
export const NEW_SERVICE = 'New Service';
export const HOME = 'Home';
export const SELECT_SERVICES = 'Select Services';
export const SETTINGS = 'Settings';
